apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: user-platform
  labels:
    app: user-platform-api
type: Opaque
stringData:
  db-password: "20122002"
  metrics-api-key: "your_metrics_api_key_here"
