apiVersion: v1
kind: Service
metadata:
  name: user-platform-api
  namespace: user-platform
  labels:
    app: user-platform-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30100
    protocol: TCP
    name: http
  selector:
    app: user-platform-api
